const mongoose = require("./dbs/connection");
const db = mongoose.connection;
const Food = require("./models/Food");

db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  // await Food.deleteMany({});

  const foods = [
    {
      name: "apple",
      calories: 125,
      Servings: 1,
      totalFat: 17,
      carbs: 125,
      protein: 2,
      cholesterol: 51,
      sodium: 331,
      potassium: 147,
      Link: "apple.com",
    },
    {
      name: "Garlic Sesame Broccoli Rabe with Panko Crusted Chicken",
      calories: 197,
      Servings: 8,
      totalFat: 12,
      carbs: 10,
      protein: 13,
      cholesterol: 72,
      sodium: 271,
      potassium: 270,
      Link:
        "https://www.edamam.com/recipe/garlic-sesame-broccoli-rabe-with-panko-crusted-chicken-a9d71387365bea12e55269a989b75ab6/most+searched",
    },
    {
      name: "Italian Stuffed Chicken",
      calories: 611,
      Servings: 4,
      totalFat: 30,
      carbs: 7,
      protein: 75,
      cholesterol: 250,
      sodium: 455,
      potassium: 0,
      Link:
        "https://www.edamam.com/recipe/italian-stuffed-chicken-d2a222524abc1c65389e31514cee6e73/most+searched",
    },
    {
      name: "Butterscotch Pudding",
      calories: 217,
      Servings: 8,
      totalFat: 13,
      carbs: 21,
      protein: 3,
      cholesterol: 111,
      sodium: 230,
      potassium: 141,
      Link:
        "https://www.edamam.com/recipe/butterscotch-pudding-searching-for-the-perfect-recipe-6fdf05550432530fda9a218e66d7aaf4/most+searched",
    },
    {
      name: "Red Lobster Biscuits",
      calories: 195,
      Servings: 12,
      totalFat: 11,
      carbs: 21,
      protein: 4,
      cholesterol: 23,
      sodium: 244,
      potassium: 62,
      Link:
        "https://www.edamam.com/recipe/red-lobster-s-cheddar-bay-biscuits-4395874613d06a1028d15a37a5ac324a/most+searched",
    },
    {
      name: "Baked Mac and Cheese",
      calories: 284,
      Servings: 12,
      totalFat: 17,
      carbs: 17,
      protein: 15,
      cholesterol: 51,
      sodium: 331,
      potassium: 147,
      Link:
        "https://www.edamam.com/recipe/easiest-baked-mac-and-cheese-9517d8e497e6b98127ad4ef917338be2/most+searched",
    },
    {
      name: "Chicken Breast with Orange and Gaeta Olives",
      calories: 338,
      Servings: 6,
      totalFat: 21,
      carbs: 8,
      protein: 25,
      cholesterol: 83,
      sodium: 500,
      potassium: 353,
      Link:
        "https://www.edamam.com/recipe/chicken-breast-with-orange-and-gaeta-olives-pollo-con-olive-ed-aranci-cdc26e3ec61c1be968d478b9a8a0ff95/most+searched",
    },
    {
      name: "Minced Chicken in Lettuce Cups",
      calories: 1128,
      Servings: 2,
      totalFat: 79,
      carbs: 14,
      protein: 87,
      cholesterol: 340,
      sodium: 1402,
      potassium: 1366,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-minced-chicken-in-lettuce-cups-recipe-999479c47b9f01ad5c9bdadc8cef80f1/most+searched",
    },
    {
      name: "Graham Crackers",
      calories: 384,
      Servings: 10,
      totalFat: 1,
      carbs: 85,
      protein: 7,
      cholesterol: 2,
      sodium: 265,
      potassium: 1191,
      Link:
        "https://www.edamam.com/recipe/graham-crackers-ce55b5a98db10ddaeeec2d3f118d4703/most+searched",
    },
    {
      name: "Pain a l' Ancienne",
      calories: 812,
      Servings: 4,
      totalFat: 8,
      carbs: 155,
      protein: 28,
      cholesterol: 0,
      sodium: 857,
      potassium: 310,
      Link:
        "https://www.edamam.com/recipe/pain-a-l-ancienne-321d1742b318f471085afc02650bda4c/most+searched",
    },
    {
      name: "Asparagus with Chorizo and Croutons",
      calories: 683,
      Servings: 4,
      totalFat: 32,
      carbs: 75,
      protein: 27,
      cholesterol: 25,
      sodium: 1246,
      potassium: 710,
      Link:
        "https://www.edamam.com/recipe/asparagus-with-chorizo-and-croutons-c27beab6034832d7f96cb4f12dd97c73/most+searched",
    },
    {
      name: "Raw Chocolate Chip Cookies",
      calories: 326,
      Servings: 20,
      totalFat: 16,
      carbs: 44,
      protein: 8,
      cholesterol: 2,
      sodium: 196,
      potassium: 365,
      Link:
        "https://www.edamam.com/recipe/raw-chocolate-chip-cookies-2a1d4c7cc6cf469cfe929ca6be537d09/most+searched",
    },
    {
      name: "Chipotle Beef Tacos",
      calories: 491,
      Servings: 4,
      totalFat: 22,
      carbs: 45,
      protein: 30,
      cholesterol: 77,
      sodium: 680,
      potassium: 824,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-chipotle-beef-tacos-recipe-f1e595cd1c56b54bea4e0b41bd5ebd31/most+searched",
    },
    {
      name: "Soba Salad with Miso Dressing",
      calories: 522,
      Servings: 8,
      totalFat: 30,
      carbs: 57,
      protein: 13,
      cholesterol: 23,
      sodium: 1358,
      potassium: 646,
      Link:
        "https://www.edamam.com/recipe/soba-salad-with-miso-dressing-f30c15533ce9d6ccc70297c52f73c3ad/most+searched",
    },
    {
      name: "Pork Braised in Guajillo Chile Sauce",
      calories: 646,
      Servings: 8,
      totalFat: 51,
      carbs: 5,
      protein: 40,
      cholesterol: 161,
      sodium: 671,
      potassium: 793,
      Link:
        "https://www.edamam.com/recipe/pork-braised-in-guajillo-chile-sauce-4346f7707bf0a2162a00d300a6c7a2d3/most+searched",
    },
    {
      name: "Curried Butternut Soup",
      calories: 199,
      Servings: 6,
      totalFat: 6,
      carbs: 32,
      protein: 8,
      cholesterol: 7,
      sodium: 903,
      potassium: 736,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-curried-butternut-soup-recipe-85fab979816c27a4556daaaca9f38db7/most+searched",
    },
    {
      name: "Sesame Balls with Druken Fig Filling",
      calories: 197,
      Servings: 25,
      totalFat: 3,
      carbs: 40,
      protein: 3,
      cholesterol: 0,
      sodium: 143,
      potassium: 246,
      Link:
        "https://www.edamam.com/recipe/sesame-balls-with-drunken-fig-filling-7ee5dc45a98c7e9fcf97a612b57760f7/most+searched",
    },
    {
      name: "Rich Buttermilk Waffles",
      calories: 403,
      Servings: 6,
      totalFat: 25,
      carbs: 38,
      protein: 8,
      cholesterol: 109,
      sodium: 368,
      potassium: 162,
      Link:
        "https://www.edamam.com/recipe/rich-buttermilk-waffles-e8e3fc2ec61fcaaddaeb595220aa968a/most+searched",
    },
    {
      name: "Hanger Steak with Shallots and Mushrooms",
      calories: 564,
      Servings: 4,
      totalFat: 38,
      carbs: 14,
      protein: 39,
      cholesterol: 126,
      sodium: 920,
      potassium: 986,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-hanger-steak-with-shallots-and-mushrooms-bfd16c8583d4232ef31aad43ee9cb6c8/most+searched",
    },
    {
      name: "Mango Sticky Rice",
      calories: 638,
      Servings: 4,
      totalFat: 13,
      carbs: 123,
      protein: 9,
      cholesterol: 0,
      sodium: 605,
      potassium: 516,
      Link:
        "https://www.edamam.com/recipe/mango-sticky-rice-c459c9d691792e58050814cd9810463c/most+searched",
    },
    {
      name: "Flaky Blood Orange Tart",
      calories: 294,
      Servings: 14,
      totalFat: 17,
      carbs: 35,
      protein: 2,
      cholesterol: 62,
      sodium: 93,
      potassium: 143,
      Link:
        "https://www.edamam.com/recipe/flaky-blood-orange-tart-14da6321aed0360d8d118ba19fb2a245/most+searched",
    },
    {
      name: "Summer's Last Hurrah Panzanella",
      calories: 228,
      Servings: 8,
      totalFat: 15,
      carbs: 20,
      protein: 4,
      cholesterol: 0,
      sodium: 388,
      potassium: 263,
      Link:
        "https://www.edamam.com/recipe/summer-s-last-hurrah-panzanella-fa2715792a3aa96593e604a393a4c8a6/most+searched",
    },
    {
      name: "Parsley Leaf Potatoes",
      calories: 168,
      Servings: 10,
      totalFat: 7,
      carbs: 25,
      protein: 3,
      cholesterol: 18,
      sodium: 443,
      potassium: 573,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-chinese-steamed-trout-with-fermented-black-beans-recipe-2fb4c3cbd84706712f5fb6080af4b228/most+searched",
    },
    {
      name: "Russian Honey Cake",
      calories: 301,
      Servings: 22,
      totalFat: 15,
      carbs: 38,
      protein: 5,
      cholesterol: 64,
      sodium: 137,
      potassium: 162,
      Link:
        "https://www.edamam.com/recipe/russian-honey-cake-ca44c643571433236d196ed85c10eed7/most+searched",
    },
    {
      name: "Apple Cranberry Crisp",
      calories: 314,
      Servings: 12,
      totalFat: 9,
      carbs: 57,
      protein: 3,
      cholesterol: 36,
      sodium: 204,
      potassium: 172,
      Link:
        "https://www.edamam.com/recipe/apple-cranberry-crisp-86d7762fa41764c98ac5eb34d28b033f/most+searched",
    },
    {
      name: "Fried Squid with Marinara Sauce",
      calories: 928,
      Servings: 4,
      totalFat: 57,
      carbs: 59,
      protein: 43,
      cholesterol: 530,
      sodium: 936,
      potassium: 719,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-fried-squid-with-marinara-sauce-recipe-45337c7d8febfd3d1695ceea5ab50a79/most+searched",
    },
    {
      name: "Italian Stuffed Cabbage",
      calories: 233,
      Servings: 10,
      totalFat: 15,
      carbs: 16,
      protein: 11,
      cholesterol: 31,
      sodium: 438,
      potassium: 443,
      Link:
        "https://www.edamam.com/recipe/italian-stuffed-cabbage-58f8ca967b8c48f824bcdbf0a0b8ca83/most+searched",
    },
    {
      name: "Bon Bon Chicken Recipe",
      calories: 297,
      Servings: 4,
      totalFat: 10,
      carbs: 9,
      protein: 40,
      cholesterol: 124,
      sodium: 740,
      potassium: 853,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-bon-bon-chicken-recipe-45560395538a71f6e72ea33e88c2511c/most+searched",
    },
    {
      name: "Creamy Scrambled Eggs with Caviar",
      calories: 206,
      Servings: 4,
      totalFat: 14,
      carbs: 11,
      protein: 10,
      cholesterol: 243,
      sodium: 320,
      potassium: 151,
      Link:
        "https://www.edamam.com/recipe/creamy-scrambled-eggs-with-caviar-recipe-1df4d1dca63319e67210269877918395/most+searched",
    },
    {
      name: "Chocolate Layer Cake",
      calories: 374,
      Servings: 56,
      totalFat: 21,
      carbs: 47,
      protein: 4,
      cholesterol: 63,
      sodium: 247,
      potassium: 180,
      Link:
        "https://www.edamam.com/recipe/layer-cake-tips-the-biggest-birthday-cake-yet-7bafcc14bdd8a3d5640a8b5ebb5123b0/most+searched",
    },
    {
      name: "Lemon Linguine",
      calories: 281,
      Servings: 12,
      totalFat: 15,
      carbs: 29,
      protein: 8,
      cholesterol: 6,
      sodium: 161,
      potassium: 108,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-lemon-linguine-recipe-2b8d35cdb82b4c96cdaaa50868127026/most+searched",
    },
    {
      name: "Chili",
      calories: 547,
      Servings: 6,
      totalFat: 33,
      carbs: 25,
      protein: 33,
      cholesterol: 107,
      sodium: 1037,
      potassium: 1068,
      Link:
        "https://www.edamam.com/recipe/cook-the-book-chili-4fe0cdd2f44658d52009afe45bcc4305/most+searched",
    },
    {
      name: "Baked Potatoes with Broccoli and Cheddar",
      calories: 554,
      Servings: 4,
      totalFat: 31,
      carbs: 50,
      protein: 22,
      cholesterol: 72,
      sodium: 1043,
      potassium: 1386,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-baked-potatoes-with-broccoli-and-cheddar-recipe-c357db5b5954daeda5ad97332925e430/most+searched",
    },
    {
      name: "Scalloped Potatoes",
      calories: 211,
      Servings: 6,
      totalFat: 13,
      carbs: 20,
      protein: 5,
      cholesterol: 42,
      sodium: 364,
      potassium: 461,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-scalloped-potatoes-recipe-40ace740d17b4e0a10e95df3246f9545/most+searched",
    },
    {
      name: "Chipotle and Tomatillo Salsa",
      calories: 39,
      Servings: 2,
      totalFat: 1,
      carbs: 9,
      protein: 1,
      cholesterol: 0,
      sodium: 1285,
      potassium: 343,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-chipotle-and-tomatillo-salsa-recipe-a9162dba0f23afab85a914e9d9fa829e/most+searched",
    },
    {
      name: "Pork Tacos with Poblano and Tomatillo Salsa",
      calories: 260,
      Servings: 8,
      totalFat: 11,
      carbs: 28,
      protein: 14,
      cholesterol: 36,
      sodium: 441,
      potassium: 441,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-pork-tacos-with-poblano-and-tomatillo-salsa-recipe-627df6298af6470a24b7521f15c0e2f8/most+searched",
    },
    {
      name: "Bucatini with Sausage",
      calories: 510,
      Servings: 6,
      totalFat: 16,
      carbs: 64,
      protein: 24,
      cholesterol: 28,
      sodium: 600,
      potassium: 633,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-bucatini-con-salsicce-bucatini-with-sausage-recipe-839a4c6cbd05a7584a1c0134933e631a/most+searched",
    },
    {
      name: "Chipotle Shrimp Tostadas",
      calories: 189,
      Servings: 6,
      totalFat: 9,
      carbs: 16,
      protein: 13,
      cholesterol: 100,
      sodium: 495,
      potassium: 486,
      Link:
        "https://www.edamam.com/recipe/dinner-tonight-chipotle-shrimp-tostadas-recipe-f3c977ce1d1bd53f860e690eb85a2825/most+searched",
    },
    {
      name: "Apple Crisp",
      calories: 502,
      Servings: 8,
      totalFat: 24,
      carbs: 72,
      protein: 4,
      cholesterol: 61,
      sodium: 29,
      potassium: 273,
      Link:
        "https://www.edamam.com/recipe/classic-apple-crisp-for-thanksgiving-recipe-b149d6583e6f5566e5019dea00b29f0e/most+searched",
    },
    {
      name: "Homeade Pita Bread with Goat Cheese and Peppers",
      calories: 236,
      Servings: 8,
      totalFat: 5,
      carbs: 42,
      protein: 8,
      cholesterol: 0,
      sodium: 248,
      potassium: 130,
      Link:
        "https://www.edamam.com/recipe/sack-lunch-homemade-pita-bread-with-goat-cheese-and-peppers-903ea54ca4d98252ef14753e6a96e701/most+searched",
    },
    {
      name: "Homemade Peppermint Patties",
      calories: 119,
      Servings: 20,
      totalFat: 5,
      carbs: 19,
      protein: 1,
      cholesterol: 4,
      sodium: 2,
      potassium: 43,
      Link:
        "https://www.edamam.com/recipe/healthy-delicious-homemade-peppermint-patties-recipe-59e02d64eb866c4aba14a5020e1c4d0f/most+searched",
    },
    {
      name: "Gluten Free Teff",
      calories: 140,
      Servings: 4,
      totalFat: 3,
      carbs: 25,
      protein: 3,
      cholesterol: 8,
      sodium: 88,
      potassium: 127,
      Link:
        "https://www.edamam.com/recipe/gluten-free-tuesday-teff-recipe-08793afa743f415b447e47fe1f0e6ae6/most+searched",
    },
    {
      name: "Red Velvet Cake",
      calories: 338,
      Servings: 28,
      totalFat: 20,
      carbs: 40,
      protein: 3,
      cholesterol: 56,
      sodium: 174,
      potassium: 57,
      Link:
        "https://www.edamam.com/recipe/a-red-velvet-affair-recipe-c0ce53a6f9f2a1b323b7376b287ecc2a/most+searched",
    },
    {
      name: "Southern Black-Eyed Peas with Bacon",
      calories: 141,
      Servings: 8,
      totalFat: 7,
      carbs: 15,
      protein: 4,
      cholesterol: 12,
      sodium: 253,
      potassium: 340,
      Link:
        "https://www.edamam.com/recipe/healthy-and-delicious-southern-style-black-eyed-peas-with-bacon-recipe-a6a343e6e447e69deb285a6532816c4b/most+searched",
    },
    {
      name: "Macarons",
      calories: 93,
      Servings: 40,
      totalFat: 6,
      carbs: 11,
      protein: 1,
      cholesterol: 9,
      sodium: 11,
      potassium: 53,
      Link:
        "https://www.edamam.com/recipe/how-to-make-macarons-recipe-7c49b5796a95c50c45470b5103a54201/most+searched",
    },
    {
      name: "Raspberry and Pistachio Cheesecake",
      calories: 699,
      Servings: 10,
      totalFat: 54,
      carbs: 46,
      protein: 11,
      cholesterol: 237,
      sodium: 371,
      potassium: 267,
      Link:
        "https://www.edamam.com/recipe/raspberry-and-pistachio-cheesecake-4fc85fb374f99ef20d7f5671b26dac2a/most+searched",
    },
    {
      name: "Thai Ground Chicken Basil",
      calories: 327,
      Servings: 4,
      totalFat: 18,
      carbs: 15,
      protein: 28,
      cholesterol: 73,
      sodium: 937,
      potassium: 773,
      Link:
        "https://www.edamam.com/recipe/thai-ground-chicken-basil-fd6aacbcc2d6315e6781a167eaca68d9/most+searched",
    },
    {
      name: "Quick and Easy Huevos Rancheros",
      calories: 713,
      Servings: 4,
      totalFat: 39,
      carbs: 55,
      protein: 39,
      cholesterol: 385,
      sodium: 2000,
      potassium: 1125,
      Link:
        "https://www.edamam.com/recipe/quick-and-easy-huevos-rancheros-10390dc1ec57e3a438e126ef8799c107/most+searched",
    },
    {
      name: "Strawberry Avocado Kale Salad with Bacon Poppyseed Dressing",
      calories: 1455,
      Servings: 1,
      totalFat: 128,
      carbs: 77,
      protein: 13,
      cholesterol: 56,
      sodium: 989,
      potassium: 2000,
      Link:
        "https://www.edamam.com/recipe/strawberry-avocado-kale-salad-w-bacon-poppyseed-dressing-d0f12f5c9802c9689992b21ba5a180f8/most+searched",
    },
    {
      name: "Chicken Breasts with Orange Balsamic Glaze",
      calories: 293,
      Servings: 4,
      totalFat: 15,
      carbs: 17,
      protein: 19,
      cholesterol: 56,
      sodium: 70,
      potassium: 390,
      Link:
        "https://www.edamam.com/recipe/chicken-breasts-with-orange-balsamic-glaze-0df2fc4a3401588dc1cfb87846c37bac/most+searched",
    },
    {
      name: "Cincinnati Chili",
      calories: 197,
      Servings: 8,
      totalFat: 7,
      carbs: 9,
      protein: 26,
      cholesterol: 70,
      sodium: 762,
      potassium: 664,
      Link:
        "https://www.edamam.com/recipe/lauren-s-cincinnati-chili-6f6e05b20a50cabcbc6fe928c346ea2f/most+searched",
    },
    {
      name: "Chocolate Peanut Butter Bars",
      calories: 657,
      Servings: 9,
      totalFat: 37,
      carbs: 79,
      protein: 10,
      cholesterol: 73,
      sodium: 15,
      potassium: 278,
      Link:
        "https://www.edamam.com/recipe/chocolate-peanut-butter-bars-a3ad29f944c9fd16b8de58e3c2c52836/most+searched",
    },
    {
      name: "Oreo-Graham Marshmallow Cupcakes",
      calories: 396,
      Servings: 12,
      totalFat: 22,
      carbs: 51,
      protein: 4,
      cholesterol: 68,
      sodium: 91,
      potassium: 155,
      Link:
        "https://www.edamam.com/recipe/oreo-graham-marshmallow-cupcakes-5d3ec01cc847c588134c820163512065/most+searched",
    },
    {
      name: "Apple",
      calories: 95,
      Servings: 1,
      totalFat: 0,
      carbs: 25,
      protein: 0,
      cholesterol: 0,
      sodium: 2,
      potassium: 195,
      Link: "https://wizard.edamam.com/free/#nutrients:7",
    },
    {
      name: "Orange",
      calories: 61,
      Servings: 1,
      totalFat: 0,
      carbs: 15,
      protein: 1,
      cholesterol: 0,
      sodium: 0,
      potassium: 237,
      Link: "https://wizard.edamam.com/free/#nutrients:8",
    },
    {
      name: "Banana",
      calories: 103,
      Servings: 1,
      totalFat: 0,
      carbs: 26,
      protein: 1,
      cholesterol: 0,
      sodium: 1,
      potassium: 414,
      Link: "https://wizard.edamam.com/free/#nutrients:9",
    },
    {
      name: "Grapefruit",
      calories: 78,
      Servings: 1,
      totalFat: 0,
      carbs: 20,
      protein: 2,
      cholesterol: 0,
      sodium: 0,
      potassium: 349,
      Link: "https://wizard.edamam.com/free/#nutrients:10",
    },
    {
      name: "Grape",
      calories: 3,
      Servings: 1,
      totalFat: 0,
      carbs: 1,
      protein: 0,
      cholesterol: 0,
      sodium: 0,
      potassium: 9,
      Link: "https://wizard.edamam.com/free/#nutrients:11",
    },
    {
      name: "Kiwi",
      calories: 42,
      Servings: 1,
      totalFat: 0,
      carbs: 10,
      protein: 1,
      cholesterol: 0,
      sodium: 2,
      potassium: 215,
      Link: "https://wizard.edamam.com/free/#nutrients:12",
    },
    {
      name: "Plum",
      calories: 31,
      Servings: 1,
      totalFat: 0,
      carbs: 8,
      protein: 0,
      cholesterol: 0,
      sodium: 0,
      potassium: 104,
      Link: "https://wizard.edamam.com/free/#nutrients:13",
    },
    {
      name: "Melon",
      calories: 188,
      Servings: 1,
      totalFat: 1,
      carbs: 45,
      protein: 5,
      cholesterol: 0,
      sodium: 88,
      potassium: 1474,
      Link: "https://wizard.edamam.com/free/#nutrients:14",
    },
    {
      name: "Watermelon",
      calories: 338,
      Servings: 0.25,
      totalFat: 2,
      carbs: 85,
      protein: 7,
      cholesterol: 0,
      sodium: 11,
      potassium: 1265,
      Link: "https://wizard.edamam.com/free/#nutrients:16",
    },
    {
      name: "Cantaloupe",
      calories: 188,
      Servings: 1,
      totalFat: 1,
      carbs: 45,
      protein: 5,
      cholesterol: 0,
      sodium: 88,
      potassium: 1474,
      Link: "https://wizard.edamam.com/free/#nutrients:18",
    },
    {
      name: "Pear",
      calories: 106,
      Servings: 1,
      totalFat: 0,
      carbs: 28,
      protein: 1,
      cholesterol: 0,
      sodium: 2,
      potassium: 216,
      Link: "https://wizard.edamam.com/free/#nutrients:19",
    },
    {
      name: "Avocado",
      calories: 322,
      Servings: 1,
      totalFat: 29,
      carbs: 17,
      protein: 4,
      cholesterol: 0,
      sodium: 14,
      potassium: 975,
      Link: "https://wizard.edamam.com/free/#nutrients:20",
    },
    {
      name: "Yogurt",
      calories: 139,
      Servings: 1,
      totalFat: 7,
      carbs: 11,
      protein: 8,
      cholesterol: 30,
      sodium: 104,
      potassium: 352,
      Link: "https://wizard.edamam.com/free/#nutrients:21",
    },
    {
      name: "Hard Boiled Egg",
      calories: 62,
      Servings: 1,
      totalFat: 4,
      carbs: 0,
      protein: 5,
      cholesterol: 149,
      sodium: 50,
      potassium: 50,
      Link: "https://wizard.edamam.com/free/#nutrients:22",
    },
    {
      name: "Scrambled Egg",
      calories: 72,
      Servings: 1,
      totalFat: 5,
      carbs: 1,
      protein: 5,
      cholesterol: 135,
      sodium: 71,
      potassium: 64,
      Link: "https://wizard.edamam.com/free/#nutrients:23",
    },
    {
      name: "Egg white",
      calories: 13,
      servings: 1,
      totalFat: 0,
      carbs: 0,
      protein: 3,
      cholesterol: 0,
      sodium: 44,
      potassium: 43,
      Link: "https://wizard.edamam.com/free/#nutrients:24",
    },
    {
      name: "Oatmeal",
      calories: 307,
      servings: 1,
      totalFat: 5,
      carbs: 55,
      protein: 11,
      cholesterol: 0,
      sodium: 5,
      potassium: 293,
      Link: "https://wizard.edamam.com/free/#nutrients:25",
    },
    {
      name: "The Wrangler Breakfast Taco Recipe",
      calories: 302,
      servings: 18,
      totalFat: 24,
      carbs: 2,
      protein: 19,
      cholesterol: 114,
      sodium: 110,
      potassium: 308,
      Link:
        "https://www.edamam.com/recipe/the-wrangler-breakfast-taco-recipe-58e7db4ee100518bcb39651514cf962a/breakfast",
    },
    {
      name: "Breakfast Sausage Puffs",
      calories: 199,
      Servings: 8,
      totalFat: 16,
      carbs: 5,
      protein: 10,
      cholesterol: 59,
      sodium: 432,
      potassium: 193,
      Link:
        "https://www.edamam.com/recipe/breakfast-sausage-puffs-63ccc00c3c1051750933c9ad8fb9e987/breakfast",
    },
    {
      name: "Breakfast Patty Melt",
      calories: 688,
      Servings: 2,
      totalFat: 56,
      carbs: 18,
      protein: 28,
      cholesterol: 304,
      sodium: 903,
      potassium: 369,
      Link:
        "https://www.edamam.com/recipe/breakfast-patty-melt-recipes-da57ba7e791f6848a9f0607ab2f4d2d6/breakfast",
    },
    {
      name: "Sausage and Potato Breakfast Casserole",
      calories: 436,
      Servings: 6,
      totalFat: 30,
      carbs: 20,
      protein: 22,
      cholesterol: 87,
      sodium: 769,
      potassium: 682,
      Link:
        "https://www.edamam.com/recipe/sausage-and-potato-breakfast-casserole-2a6125db43a0cfa7378d4c96b1a021f7/breakfast",
    },
    {
      name: "Breakfast Sausage, Mushroom, and Cheddar Rolls Recipe",
      calories: 364,
      Servings: 10,
      totalFat: 26,
      carbs: 22,
      protein: 10,
      cholesterol: 40,
      sodium: 381,
      potassium: 222,
      Link:
        "https://www.edamam.com/recipe/breakfast-sausage-mushroom-and-cheddar-rolls-recipe-80ffa6f067ed26dd624de1afcc838448/breakfast",
    },
    {
      name: "Breakfast Focaccia",
      calories: 715,
      Servings: 7,
      totalFat: 35,
      carbs: 73,
      protein: 26,
      cholesterol: 188,
      sodium: 656,
      potassium: 374,
      Link:
        "https://www.edamam.com/recipe/breakfast-focaccia-recipes-bf7f5d9e327aa706986e6f717c053bbd/breakfast",
    },
    {
      name: "Tropical Breakfast Parfait",
      calories: 160,
      Servings: 4,
      totalFat: 2,
      carbs: 31,
      protein: 7,
      cholesterol: 6,
      sodium: 109,
      potassium: 348,
      Link:
        "https://www.edamam.com/recipe/tropical-breakfast-parfait-c19d40657bc8143f784e5a6e3bbd6353/breakfast",
    },
    {
      name: "Breakfast Nachos",
      calories: 918,
      Servings: 4,
      totalFat: 71,
      carbs: 47,
      protein: 27,
      cholesterol: 271,
      sodium: 1790,
      potassium: 1547,
      Link:
        "https://www.edamam.com/recipe/breakfast-nachos-recipes-b8615f457778d374141a7666eea7a1c3/breakfast",
    },
    {
      name: "Potato, Sausage and Spinach Breakfast Casserole",
      calories: 613,
      Servings: 8,
      totalFat: 47,
      carbs: 19,
      protein: 29,
      cholesterol: 491,
      sodium: 866,
      potassium: 940,
      Link:
        "https://www.edamam.com/recipe/potato-sausage-and-spinach-breakfast-casserole-2d50d9a19511f49956a8979eec80130f/breakfast",
    },
    {
      name: "Pistachio Breakfast Sausage Patties",
      calories: 174,
      Servings: 8,
      totalFat: 13,
      carbs: 3,
      protein: 12,
      cholesterol: 38,
      sodium: 229,
      potassium: 281,
      Link:
        "https://www.edamam.com/recipe/pistachio-breakfast-sausage-patties-recipes-ecb4b5ee82072f5b275e16a52dbf38fe/breakfast",
    },
  ];

  await Food.insertMany(foods);
  console.log("Created some food items!");
};
const run = async () => {
  await main();
  db.close();
};

run();
